name: build-and-publish-page

env:
  PUBLISH_DIR: src/bin/Release/net6.0/publish/wwwroot
on:
  workflow_dispatch:
  push:
    paths: src/**
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true 
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        include-prerelease: true
    - name: Setup workloads
      run: dotnet workload restore
    - name: Publish app
      run: dotnet publish -c Release
        
    - name: Create CNAME file
      run: echo "seal.report" > ${{ env.PUBLISH_DIR }}/CNAME
      
    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2.6.0
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
