name: build-and-publish-page

env:
  PUBLISH_DIR: src/bin/Release/net7.0/publish/wwwroot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true 
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
        include-prerelease: true
    - name: Publish app
      run: dotnet publish -c Release
      
    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /seal-report/
        
    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2.6.0
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
